CREATE TABLE Recipe (
    RecipeID SERIAL PRIMARY KEY,

    RecipeName VARCHAR(150) NOT NULL,

    Category VARCHAR(50) NOT NULL,

    Instructions TEXT,

    Notes TEXT,

    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);